### ISSUE TITLE
Update config.py to include version

### ISSUE THREAD

**Issue by ekatzenstein** [camerahacks/ccapi-octolapse#1]
When attempting to connect via rpi, I get the error below. Version needs to be added to `config.py`. I'll cut a PR if I get it working. Awesome project!

```	Traceback (most recent call last):
	  File "/home/pi/scripts/ccapi-trigger.py", line 18, in <module>
	    shutter()
	  File "/home/pi/scripts/ccapi-trigger.py", line 12, in shutter
	    endpoint = '/ccapi/ver'+str(config.VERSION)+'/shooting/control/shutterbutton'
	AttributeError: module 'config' has no attribute 'VERSION'
2022-05-01 19:24:55,698 - octolapse.script - ERROR - Error output (stderr) for 'CCAPI - Snapshot Camera Script':
	Traceback (most recent call last):
	  File "/home/pi/scripts/ccapi-trigger.py", line 18, in <module>
	    shutter()
	  File "/home/pi/scripts/ccapi-trigger.py", line 12, in shutter
	    endpoint = '/ccapi/ver'+str(config.VERSION)+'/shooting/control/shutterbutton'
	AttributeError: module 'config' has no attribute 'VERSION'
```

**Comment by ekatzenstein** [comment]
Merged
